# Generated by Django 4.2.1 on 2023-09-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_end_date_student_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='end_date',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='start_date',
            new_name='start_year',
        ),
    ]
