# Generated by Django 4.2.1 on 2023-09-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_end_date_student_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address_of_guardian',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address_of_next_of_kin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email_of_guardian',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email_of_next_of_kin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='former_surname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='next_of_kin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='permanent_home_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number_of_guardian',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number_of_next_of_kin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='place_of_origin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='start_year',
        ),
        migrations.AlterField(
            model_name='student',
            name='room_capacity_preference',
            field=models.PositiveIntegerField(),
        ),
    ]
