# Generated by Django 4.2.1 on 2023-09-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_student_address_of_guardian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address_of_guardian',
            field=models.CharField(default='hj', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='address_of_next_of_kin',
            field=models.CharField(default='kjh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='contact_address',
            field=models.CharField(default='gf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_of_guardian',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_of_next_of_kin',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='former_surname',
            field=models.CharField(default=8, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.CharField(default=8, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status',
            field=models.CharField(default=8, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='next_of_kin',
            field=models.CharField(default=8, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_home_address',
            field=models.CharField(default=9, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=9, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number_of_guardian',
            field=models.CharField(default=9, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number_of_next_of_kin',
            field=models.CharField(default=7, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(default=6, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_origin',
            field=models.CharField(default=7, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_capacity_preference',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
